name             'monit'
maintainer       'Mikhail Kozorovitskiy'
maintainer_email 'mikhail@thecrazyrussian.com'
license          'All rights reserved'
description      'Installs/Configures apt'
version          '0.1.0'
