name             'react'
maintainer       'Mikhail Kozorovitskiy'
maintainer_email 'mikhail@thecrazyrussian.com'
license          'All rights reserved'
description      'Installs/Configures React'
version          '0.1.0'
depends		 'nginx'
